### ISSUE TITLE
Feature: allow GH pkg builds (e.g. for pkgs using rust)

### ISSUE THREAD

**Issue by philipp-baumann** [rstudio/renv#1572]
I am currently using {renv} on [renkulab.io](https://renkulab.io). The Dockerfile template I am using is based on Ubuntu 20.04. Since I want to install {polars}, I need to do that from source. For this, I get the latest stable Rust edition. 

However, the build process is way too long. Therefore, I was wondering if you plan to support GH builds of packages in {renv}? 

Here is an example of the failing build: https://renkulab.io/gitlab/philipp.baumann/applied-infrared-spectroscopic-modeling-workshop-for-soil-and-plant-diagnostics/-/jobs/650410

Here are the corresponding `renv.lock` lines

```yaml
    "polars": {
      "Package": "polars",
      "Version": "0.6.1",
      "Source": "unknown",
      "Hash": "bf70ffe63203bdebb409bf57856a328f",
      "Requirements": [
        "codetools"
      ]
    }
```
