### ISSUE TITLE
`renv::install()` fails when CRAN-like repositories are in `renv.lock`

### ISSUE THREAD

**Issue by ezraporter** [rstudio/renv#1578]
My institution uses a [`drat`](https://eddelbuettel.github.io/drat/) repository in our GitHub Enterprise to distribute packages internally. Since `renv 0.17.0` `renv::install()` seems to fail for **any** package (even CRAN packages) when our `drat` repo is in my `renv.lock`.

I did some digging and it seems like the regression may have occurred at https://github.com/rstudio/renv/commit/62c73d9c74117ceafec37c8e4a5c343aed149792 where a warning was upgraded to an error in [`available-packages.R`](https://github.com/rstudio/renv/blob/62c73d9c74117ceafec37c8e4a5c343aed149792/R/available-packages.R#L58).

## reprex

I created a `drat` repo at https://ezraporter.github.io/drat to show the issue:

`renv.lock`:
``` yaml
...
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      },
      {
        "Name": "OTHERAN",
        "URL": "https://ezraporter.github.io/drat"
      }
    ]
  ...
```

```r
# Fails
renv::install("dplyr")
```
<details>
<summary>Show error message</summary>

```r
Error: package 'dplyr' is not available
Traceback (most recent calls last):
15: renv::install("dplyr")
14: retrieve(packages)
13: handler(package, renv_retrieve_impl(package))
12: renv_retrieve_impl(package)
11: withCallingHandlers(renv_available_packages_latest(package), 
        error = function(err) stopf("package '%s' is not available", 
            package))
10: renv_available_packages_latest(package)
 9: map(errors$data(), warning)
 8: lapply(x, f, ...)
 7: FUN(X[[i]], ...)
 6: withRestarts({
        .Internal(.signalCondition(cond, message, call))
        .Internal(.dfltWarn(message, call))
    }, muffleWarning = function() NULL)
 5: withOneRestart(expr, restarts[[1L]])
 4: doWithOneRestart(return(expr), restart)
 3: <condition-handler>(...)
 2: stopf("package '%s' is not available", package)
 1: stop(sprintf(fmt, ...), call. = call.)
```
</details>

```r
# Works but issues some warning messages due to the drat repo not serving binaries
utils::install.packages("dplyr")

#> ...
#> Warning: unable to access index for repository https://ezraporter.github.io/drat/bin/macosx/big-sur-arm64/contrib/4.2:
#>  cannot open URL 'https://ezraporter.github.io/drat/bin/macosx/big-sur-arm64/contrib/4.2/PACKAGES'
#> ...
```

Ideally `renv` would also be able to install and track sources for packages downloaded from `drat` repos.

In `renv 0.16.0`, this works:

```r
renv::install("dummypackage")
```

where `dummypackage` is a package in https://ezraporter.github.io/drat. `renv::snapshot()` generates the right thing in my `renv.lock`:

```yaml
...
"Packages": {
    "dummypackage": {
      "Package": "dummypackage",
      "Version": "0.1.0",
      "Source": "Repository",
      "Repository": "OTHERAN", # <-- repo is tracked!
      "Hash": "76b8b050c24559ba3b842a564852c5a1",
      "Requirements": []
    },
...
```

In the latest development version:

``` r
# Fails
renv::install("dummypackage")

# Works
utils::install.packages("dummypackage")
```

However, `renv::snapshot()` doesn't generate the right thing:

```yaml
...
"Packages": {
    "dummypackage": {
      "Package": "dummypackage",
      "Version": "0.1.0",
      "Source": "unknown",
      "Hash": "76b8b050c24559ba3b842a564852c5a1"
    }
...
```

## Session Info
<details>
<summary>Session Info</summary>

```
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1  tools_4.2.1     renv_1.0.0.9000
```
</details>
