### ISSUE TITLE
add a library used indirectly (by quarto) to renv?

### ISSUE THREAD

**Issue by jayhesselberth** [rstudio/renv#1672]
I am building a quarto project that uses renv.

I'd like to use the `code-linking` feature of quarto in some of documents. But during `quarto render` I see:

```r
Warning message:
In postprocess(params$input, params$format, params$output, params$preserve) :
  The downlit and xml2 packages are required for code linking
```

I don't use downlit directly in my quarto docs, so it's not in the lock file. xml2 is a requirement of another library I'm using, so it's already in the lock file.

Is there a recommended way to install downlit so that quarto can access it? I *think* I could just add a dummy file (zzz.qmd) with `library(downlit)` in it, and then `renv::snapshot()`, but wondered if there's something more robust for such a case.

**Comment by jayhesselberth** [comment]
Update: the dummy file approach works fine for me.

Another idea occurred to me: I am using the renv github action from https://github.com/r-lib/actions/tree/v2-branch/setup-renv, and it seems like the action could address this case via an `extra-packages` parameter (which it doesn't have, currently):

```yaml
steps:
- uses: actions/checkout@v3
- uses: r-lib/actions/setup-r@v2
- uses: r-lib/actions/setup-renv@v2
  with:
    extra-packages: '"downlit"'
```
