### ISSUE TITLE
"Package libcurl was not found" during Github action setup-renv on Ubuntu

### ISSUE THREAD

**Issue by aschmidt-amplify** [rstudio/renv#1885]
When setting up github actions to test on push, the workflow fails on the setup-renv step when trying to use `ubuntu-latest` as the OS. I get the following message:

```
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
```

I do not get this when I use `macos-latest` as the OS, but I was hoping to use Ubuntu. Note that I tried to add Ubuntu dependencies as a separate step before `setup-r` but that did not work:

```
- name: Install ubuntu deps
        run: sudo apt-get install -y --no-install-recommends \
          git-core \
          libssl-dev \
          libcurl4-gnutls-dev \
          curl \
          libsodium-dev \
          libxml2-dev
```

Here is my full yaml for the github workflow:

```
name: Testing R

on:
  pull_request
    
env:
  RENV_PATHS_ROOT: ~/.cache/R/renv
  R_HOME: /Library/Frameworks/R.framework/Versions/Current/Resources
  

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache R environment setup
        uses: actions/cache@v4
        with:
          path: ${{ env.R_HOME }}
          key: ${{ runner.os }}-r-setup-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-r-setup-

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Install testing dependencies
        run: Rscript -e "install.packages(c('testthat', 'here'))"
      - name: Run tests
        run: Rscript -e "source('tests/testthat.R')"
```
