### ISSUE TITLE
Loading python virtual environment within renv

### ISSUE THREAD

**Issue by davidrsch** [rstudio/renv#1986]
Hello, I will like to know if there is a standard way to restore your virtual environment in Github Actions when using also python. I have created a python virtual environment inside my renv folder:
```
renv
  |_ python
       |_ virtualenvs
            |_ renv-python-3.11
```
And in my workflow I have:
```
- name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

- name: Setup R dependencies
        uses: r-lib/actions/setup-renv@v2
```
Which returns `Error: error restoring Python packages [error code 1]` after restoring r. I am guessing this is because I haven't setup python. Is there a standard way to do this with renv?
