### ISSUE TITLE
Trouble restoring packages when binaries are out of sync

### ISSUE THREAD

**Issue by wlandau** [rstudio/renv#2141]
When I try to restore packages, `renv` sometimes downloads incompatible binaries.  This comes up a lot when I build Docker images.

I have a collection of reproducible examples in https://github.com/wlandau/stringfish-reprex (c.f. https://github.com/traversc/stringfish/issues/21#issuecomment-2935603596).

In the `main` branch, I have a simple [`renv.lock`](https://github.com/wlandau/stringfish-reprex/blob/main/renv.lock) file with `stringfish` and its dependencies:

<details>

```json
{
  "R": {
    "Version": "4.5.0",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://packagemanager.posit.co/cran/latest"
      }
    ]
  },
  "Packages": {
    "Rcpp": {
      "Package": "Rcpp",
      "Version": "1.0.13-1",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "methods",
        "utils"
      ],
      "Hash": "6b868847b365672d6c1677b1608da9ed"
    },
    "RcppParallel": {
      "Package": "RcppParallel",
      "Version": "5.1.9",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "R"
      ],
      "Hash": "f38a72a419b91faac0ce5d9eee04c120"
    },
    "renv": {
      "Package": "renv",
      "Version": "1.0.11",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "utils"
      ],
      "Hash": "47623f66b4e80b3b0587bc5d7b309888"
    },
    "stringfish": {
      "Package": "stringfish",
      "Version": "0.16.0",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "R",
        "Rcpp",
        "RcppParallel"
      ],
      "Hash": "b7eb79470319ae71d4b5ed9cd7bf7294"
    }
  }
}
```

</details>

and a simple [`.github/workflows/reprex.yaml`](https://github.com/wlandau/stringfish-reprex/blob/main/.github/workflows/reprex.yaml) file which just restores the library:

<details>

```yaml
on: [push]

name: reprex

jobs:
  reprex:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install renv.
        run: install.packages("renv")
        shell: Rscript {0}
      - name: Restore packages.
        run: renv::restore()
        shell: Rscript {0}
```

</details>

the [worker log](https://github.com/wlandau/stringfish-reprex/actions/runs/15419560909/job/43390748644) shows an error loading the dynamic library:

```r
# Downloading packages -------------------------------------------------------
- Querying repositories for available source packages ... Done!
- Downloading renv from RSPM ...                OK [2.1 Mb in 0.29s]
- Downloading Rcpp from RSPM ...                OK [2.1 Mb in 0.36s]
- Downloading RcppParallel from RSPM ...        OK [1.8 Mb in 0.45s]
- Downloading stringfish from RSPM ...          OK [414 Kb in 0.23s]
Successfully downloaded 4 packages in 2.8 seconds.

# Installing packages --------------------------------------------------------
- Installing renv ...                           OK [installed binary and cached in 0.32s]
- Installing Rcpp ...                           OK [installed binary and cached in 0.39s]
- Installing RcppParallel ...                   OK [installed binary and cached in 0.28s]
/opt/R/4.5.0/lib/R/bin/R --vanilla -s -f '/tmp/RtmpOdQyHl/renv-install-150a55e684eb.R'
================================================================================

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/runner/work/_temp/Library/.renv/1/stringfish/libs/stringfish.so':
  /home/runner/work/_temp/Library/.renv/1/stringfish/libs/stringfish.so: undefined symbol: _ZN12RcppParallel14tbbParallelForEmmRNS_6WorkerEmi
Calls: loadNamespace -> library.dynam -> dyn.load
Execution halted
```

The source versions of `Rcpp` and `RppParallel` are compatible with `stringfish`. In fact, binaries succeed if they all come from the same day:

Other branches at https://github.com/wlandau/stringfish-reprex have various versions of this experiment to try to pin down exactly when and how this happens. For example, in the GitHub Actions, this succeeds:

```yaml
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install packages.
        run: |
          install.packages("remotes")
          library(remotes)
          install_version("Rcpp", version = "1.0.13-1")
          install_version("RcppParallel", version = "5.1.9")
          install_version("stringfish", version = "0.16.0")
        shell: Rscript {0}
      - name: Load stringfish.
        run: library(stringfish)
        shell: Rscript {0}
```

but this fails with the same dynamic library error:

```yaml
          install.packages("remotes")
          library(remotes)
          install_version("Rcpp", version = "1.0.13-1")
          install_version("RcppParallel", version = "5.1.9")
          install.packages(
            "stringfish",
            repos = "https://packagemanager.posit.co/cran/__linux__/noble/2025-06-02"
          )
```

What is the best way to figure out which package repositories `renv` is actually using?
More importantly, how exactly do I reliably control the repos `renv` uses, both during `snapshot()` and `restore()`? 

In my case, reproducibility on a single machine does not matter. I am trying to create a portable project that can seamlessly shift between two different corporate instances of Posit Workbench and also restore inside a Docker image build on GitHub Actions. Unfortunately, those two corporate instances of Posit Connect default to private internal repositories that cannot be reached from a GitHub Actions workflow. I am trying to lock down a set of public repositories that stay put in the lockfile and are respected by `renv` even after many calls to `snapshot()` and `restore()` on different machines.
