### ISSUE TITLE
GitLab CI config

### ISSUE THREAD

**Issue by artemklevtsov** [rstudio/renv#348]
Hi,

Thank you for the nice package.

I wrote a working configuration for the GitLab CI. So you can modify and include it to the package documentation.

```yaml
variables:
  DOCKER_DRIVER: "overlay2"
  GIT_SUBMODULE_STRATEGY: "recursive"
  APT_DEPS: "libcurl4-openssl-dev libssl-dev libxml2-dev libicu-dev git-core qpdf pandoc pandoc-citeproc"
  RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

image: rocker/r-ver:latest

before_script:
  - apt-get update
  - apt-get -y install ${APT_DEPS}
  - Rscript -e "renv::restore()"
  - Rscript -e "blogdown::install_hugo()"

pages:
  script:
    - Rscript -e "blogdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - master
```

Build log without cache (first time): https://gitlab.com/artemklevtsov/rblog/-/jobs/447571611
Build log with working cache: https://gitlab.com/artemklevtsov/rblog/-/jobs/447587419
