### ISSUE TITLE
not using cache when building docker container

### ISSUE THREAD

**Issue by robbie-sp** [rstudio/renv#400]
Hi,

I am trying to set up Shiny apps using renv and docker and have found your [article](https://rstudio.github.io/renv/articles/docker.html) very helpful.

I am keen to use the cache to speed up image/container builds but have been struggling to get that working.  I am using a docker volume (called renv-cache) rather than a specific mount point on the host (as in the article). When I build an image, the cache builds up as expected in the docker volume. On rebuilding the image (with docker compose build --no-cache), renv::restore() still goes out to CRAN and doesn't seem to use the cache so I am not getting any speed improvements.

Any ideas would be really appreciated.

My dockerfile which builds on top of slightly modified version of the rocker/shiny image:
```
FROM shiny_base:3.6.3

# set working directory
WORKDIR /srv/shiny-server

# Setup renv
COPY renv.lock .

ENV RENV_PATHS_CACHE="/renv/cache"
ENV RENV_CONFIG_USE_CACHE=TRUE  # may not be required if already the default
RUN R -e 'renv::consent(provided=TRUE)'
RUN R -e 'renv::restore()'

# copy the app files to the image
COPY ./app /srv/shiny-server/

# Make all app files readable (solves issue when dev in Windows, but building in Ubuntu)
RUN chmod -R +r /srv/shiny-server/

EXPOSE 3838

RUN ["chmod", "+x", "/usr/bin/shiny-server.sh"]
CMD ["/usr/bin/shiny-server.sh"]
 ```

I am using docker-compose to build this in a reproducible way. I haven't figured out how to use docker-compose to do the renv::restore() at the 'docker run' stage as the article recommends:
```
version: '3'

services:
  example:
    build: .
    image: shiny-example
    ports:
      - "80:3838"
    volumes: 
      - renv-cache:/renv/cache

volumes:
  renv-cache:
    external: true
```
