### ISSUE TITLE
CI vignette: add Bitbucket, review steps

### ISSUE THREAD

**Issue by d-sci** [rstudio/renv#498]
It may be helpful to some to include in the CI vignette an example for [bitbucket pipelines](https://support.atlassian.com/bitbucket-cloud/docs/get-started-with-bitbucket-pipelines/).

Here's a prototype similar to the ones provided for other services:

```
pipelines:
  default:
    - step:
        caches:
          - renvlib
          - renvcache
        script:
          - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
          - Rscript -e "renv::restore()"
          - [your next actions here]

definitions:
  caches:
    renvlib: renv/library
    renvcache: ~/.local/share/renv
```

In actual pipelines that I've written, however, I skipped the `if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')` step which you have as an example in all of them. Somewhat related to our discussion regarding the collaboration vignette (#366 ), it seems to me that:

- if you checked in `.Rprofile` and `renv/activate.R` , the `if` will always be FALSE, because that will bootstrap everything
- if you *didn't* check those in, then `renv` won't be active yet, so while things may work, you'll be targeting your normal `.libPaths()[[1]]` instead of `renv/library` (right?)

This was a little confusing to me.
