### ISSUE TITLE
Caching performance issue with Gitlab CI/CD

### ISSUE THREAD

**Issue by DivadNojnarg** [rstudio/renv#916]
Hi there,

In the documentation, there is a starter Gitlab template:

```yaml
variables:
  RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

before_script:
  - < ... other pre-deploy steps ... >
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"
```

Most of the time, the ${RENV_PATHS_CACHE} has more than > 10000 files in my projects. This leads to very long time for job completion (> 2h if not timeout before) and is not acceptable for people in my team. 

Is there any rational behind storing this element in the cache?

I would argue that only storing the renv library is enough in most cases but maybe I missed something and would be curious to know the reason. 

If storing the renv library is enough, I'd like to add a quick note in the documentation about this possible performance issue to be aware of. it might be misleading for people beginning with the template. 

Let me know your thought.

Thanks

David
